"""Render :class:`AIContext` to per-agent markdown, with safe re-run markers.

Each generated file is wrapped in well-known markers so re-running
``changebrief ai-context init`` only updates the generated body. Anything the
developer adds *outside* the markers is preserved on regeneration.

Per-agent variation is intentionally *minimal*: a small head-matter block
tells each agent how to use the file. The body is shared so agents stay
in sync about the project.

TODO(phase 2): optional LLM refinement of the composed context. The current
pipeline is fully deterministic by design; an LLM pass would need to gate on
``--enrich`` and run *after* composition so its output can be diffed against
the deterministic baseline.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from changebrief.core.ai_context.models import AIContext


# Re-run markers. Bumping the version invalidates older generated blocks
# (so we can ship breaking template changes without leaving orphaned content).
MARKER_VERSION = "v1"
MARKER_START = f"<!-- changebrief:ai-context:start {MARKER_VERSION} -->"
MARKER_END = f"<!-- changebrief:ai-context:end {MARKER_VERSION} -->"
# Used to recognise blocks from any version when merging.
_MARKER_START_RE = "<!-- changebrief:ai-context:start"
_MARKER_END_RE = "<!-- changebrief:ai-context:end"


@dataclass(frozen=True)
class AgentTarget:
    key: str  # CLI key: claude / cursor / codex
    filename: str
    head_matter: str


AGENT_TARGETS: Dict[str, AgentTarget] = {
    "claude": AgentTarget(
        key="claude",
        filename="CLAUDE.md",
        head_matter=(
            "> **Read by Claude Code at session start.** This file is the source of truth\n"
            "> for project-specific guidance — keep it concise and high-signal.\n"
            "> Generated by `changebrief ai-context init`. See the footer to learn how to\n"
            "> add custom guidance that survives re-runs."
        ),
    ),
    "cursor": AgentTarget(
        key="cursor",
        filename="CURSOR.md",
        head_matter=(
            "> **Project-level guidance for Cursor.** Complements `.cursor/rules/*.mdc`\n"
            "> and the modern `AGENTS.md` convention. Use rules for per-file scoping;\n"
            "> use this file for project-wide context.\n"
            "> Generated by `changebrief ai-context init`."
        ),
    ),
    "codex": AgentTarget(
        key="codex",
        filename="CODEX.md",
        head_matter=(
            "> **Read by OpenAI Codex CLI at task start.** Use this for project-level\n"
            "> guidance that should apply to every Codex session in this repo.\n"
            "> Generated by `changebrief ai-context init`."
        ),
    ),
}


def render(context: AIContext, *, target: AgentTarget) -> str:
    """Render the per-agent markdown (head + generated body wrapped in markers)."""
    body = _render_body(context)
    block = f"{MARKER_START}\n\n{body}\n\n{MARKER_END}"
    footer = (
        "\n---\n\n"
        "<!-- Anything below this line is preserved on `changebrief ai-context init`. -->\n"
        "<!-- Add team-specific context, secrets policy, on-call info, etc. here.   -->\n"
    )
    return f"{target.head_matter}\n\n{block}\n{footer}"


def merge_with_existing(rendered: str, existing: Optional[str]) -> str:
    """Idempotent merge: replace the generated block in ``existing`` with the new one.

    Behavior:

    * If ``existing`` contains markers (any version) → swap only the generated
      block; preserve everything outside the markers verbatim.
    * If ``existing`` has no markers → return ``rendered`` (caller decides
      whether ``--force`` is set; this function is purely a string op).
    * If ``existing`` is ``None`` → return ``rendered``.
    """
    if not existing:
        return rendered

    start_idx = existing.find(_MARKER_START_RE)
    end_idx = existing.find(_MARKER_END_RE)
    if start_idx == -1 or end_idx == -1 or end_idx <= start_idx:
        return rendered

    end_line_break = existing.find("\n", end_idx)
    if end_line_break == -1:
        end_line_break = len(existing)

    new_start_idx = rendered.find(_MARKER_START_RE)
    new_end_idx = rendered.find(_MARKER_END_RE)
    if new_start_idx == -1 or new_end_idx == -1:
        return rendered  # defensive: never happens with our own output
    new_end_line_break = rendered.find("\n", new_end_idx)
    if new_end_line_break == -1:
        new_end_line_break = len(rendered)
    new_block = rendered[new_start_idx:new_end_line_break]

    return existing[:start_idx] + new_block + existing[end_line_break:]


def has_marker(text: str) -> bool:
    return _MARKER_START_RE in text and _MARKER_END_RE in text


# ---------------------------------------------------------------------------- internals


def _render_body(context: AIContext) -> str:
    lines = [f"# AI coding context — {context.project_name}", "", "## Overview", "", context.overview]
    for section in context.sections:
        lines.append("")
        lines.append(f"## {section.title}")
        for paragraph in section.paragraphs:
            lines.append("")
            lines.append(paragraph.strip())
        if section.bullets:
            lines.append("")
            for bullet in section.bullets:
                lines.append(_format_bullet(bullet))
    return "\n".join(lines).rstrip() + "\n"


def _format_bullet(bullet: str) -> str:
    """Render a bullet, honouring composer-supplied indentation for nesting.

    A bullet starting with whitespace is treated as already-nested markdown:
    we strip any redundant ``- `` it carries and re-emit ``  - …`` so the
    output is valid CommonMark nested-list syntax.
    """
    if bullet[:1] in (" ", "\t"):
        stripped = bullet.lstrip()
        if stripped.startswith("- "):
            stripped = stripped[2:]
        return f"  - {stripped}"
    return f"- {bullet}"
